openimis/openimis-be_py

README.md, features/steps/core.py, openIMIS/init_test_db.py, openIMIS/openIMIS/openimisconf.py, openIMIS/openIMIS/openimisurls.py, openIMIS/openIMIS/settings.py, openIMIS/openIMIS/urls.py, requirements.txt
Also testing LGTM, don't merge too quickly please.
=> Django 3 and other components upgrade

openIMIS/openIMIS/settings.py, requirements.txt
Add APscheduler to configuration and requirements
See the openimis-be_core_py for details and actual implementation
=> OMT-215 add APscheduler

openIMIS/openIMIS/settings.py, requirements.txt
TICKET: https://openimis.atlassian.net/browse/OAI-25
=> OAI-25: Added scheduled job, changed channels backend to rabbitMQ

openIMIS/openIMIS/settings.py
Developed as part of [OTC-282](https://openimis.atlassian.net/browse/OTC-282)
=> OTC-303: Added scheduled task for notification sending

.github/workflows/main.yml, script/entrypoint.sh
to avoid api and iapi doing the migration in the same time at server boot
=> Avoid migrating on api

README.md, openIMIS/developer_tools/management/commands/install_module_pypi.py
Changes:
- Added `install_module_pypi` django admin command, allowing to install modules from PyPI (available features explained in README)
- Added explanations of `install_module_pypi` and `install_module_locally` commands to README
[https://openimis.atlassian.net/browse/OE0-92](https://openimis.atlassian.net/browse/OE0-92)
=> OE0-92: Automatizing checking newest version and installing modules from PyPI

README.md, openIMIS/developer_tools/management/commands/create_calcrule_module.py, openIMIS/developer_tools/management/commands/create_openimis_module.py, openIMIS/developer_tools/skeletons/apps_calcrule.py.template, openIMIS/developer_tools/skeletons/business_apps.template, openIMIS/developer_tools/skeletons/business_services.template, openIMIS/developer_tools/skeletons/business_tests.template, openIMIS/developer_tools/skeletons/calculation_rule.py.template, openIMIS/developer_tools/skeletons/config_calcrule.py.template, openIMIS/developer_tools/skeletons/init_calcrule_module.py.template
Changes:
- Added templates to `create_openimis_module` allowing to customize created module with additional files resulting in customized modules (calculation rule, business module)
[https://openimis.atlassian.net/browse/OE0-87](https://openimis.atlassian.net/browse/OE0-87)
=> OE0-87: Skeletons adjusted to types of modules: business models / calc rules / etc. 

requirements.txt
[https://openimis.atlassian.net/browse/OPL-44](https://openimis.atlassian.net/browse/OPL-44)
Changes:
- Added `django-cryptography` as a project dependency. The library allows to create encrypted fields in the models.
=> OPL-44: Create model and CRUD Services for Subscription

README.md, openIMIS/openIMIS/settings.py, requirements.txt
TICKET: [OE0-100](https://openimis.atlassian.net/browse/OE0-100)
=> OE0-100: Added cprofile middleware to assembly

README.md
TICKET: https://openimis.atlassian.net/browse/OP-787
=> OP-787: new section in readme regarding handling common errors related to backend

openIMIS/apscheduler_runner/__init__.py, openIMIS/apscheduler_runner/admin.py, openIMIS/apscheduler_runner/apps.py, openIMIS/openIMIS/settings.py
Part of [OTC-621](https://openimis.atlassian.net/browse/OTC-621)
=> OTC-621: Scheduled tasks can be imported from modules directly

openimis.json
https://openimis.atlassian.net/browse/OP-1088
Changes:
- Self registration module removed from the repo list.
=> OP-1088: Self-registration module removed from repository list.

.github/workflows/main.yml, requirements.txt
Upgraded DRF-Spectacular to the newest version
=> Upgraded DRF-Spectacular to the newest version

openIMIS/locale/en/LC_MESSAGES/django.po
https://openimis.atlassian.net/browse/OTC-964
This PR is also a part of: https://github.com/openimis/openimis-be-claim_py/pull/80
=> OTC-964: update translations

openIMIS/openIMIS/ExceptionHandlerDispatcher.py
Ticket: https://openimis.atlassian.net/browse/OTC-1103
Changes:
- Added missing code for authentication when user is not logged
=> OTC-1103: Authentication error fix.

requirements.txt
updated requirements.txt for https://github.com/openimis/openimis-be-invoice_py
=> ISE-183: updated requirements.txt

.flake8, openIMIS/openIMIS/settings.py, requirements.txt
Added .flake8 and django_nose configuration
=> ISE-183: Sonarcloud config updates

openimis.json
https://openimis.atlassian.net/browse/CM-146
This PR updates openimis.json file.
=> CM-146: add tasks_management module

.flake8, .github/workflows/main.yml, openIMIS/openIMIS/settings.py, requirements.txt
Reverts openimis/openimis-be_py#156
=> Revert "ISE-183 OpenIMIS Sonar - Backend Module"

.flake8, .github/workflows/main.yml, openIMIS/openIMIS/settings.py, requirements.txt
Quick fix of module failing during django tests
=> ISE-183 OpenIMIS Sonar - Backend Module

requirements.txt
Ticket: https://openimis.atlassian.net/browse/ONI-62
Changes:
- Added nepali calendar dependency.
=> ONI-62: Add Nepali calendar dependency.

requirements.txt
[https://openimis.atlassian.net/browse/OP-1512](https://openimis.atlassian.net/browse/OP-1512)
=> OP-1512 Specified version of apscheduler

.github/workflows/ci_module.yml
[https://openimis.atlassian.net/browse/OP-1529](https://openimis.atlassian.net/browse/OP-1529)
=> OP-1529 Added reusable module CI

openimis.json
Reverts openimis/openimis-be_py#176
=> Revert "hotfix-update-openimis-json"

openIMIS/init_test_db.py, openIMIS/init_test_db_pg.sql
Ticket:
https://openimis.atlassian.net/browse/OTC-1113
Changes:
syntax for pssql was fixed
=> Feature/otc 1113: syntax for pssql was fixed

openIMIS/openIMIS/settings.py, requirements.txt
TICKET: https://openimis.atlassian.net/browse/CM-269
=> CM-269: Added opensearch dsl library 

.github/workflows/ci_assembly.yml, .github/workflows/ci_module.yml
Reverts openimis/openimis-be_py#190
=> Revert "Update ci_module.yml"

.gitignore, openIMIS/openIMIS/settings.py
[https://openimis.atlassian.net/browse/CM-503](https://openimis.atlassian.net/browse/CM-503)
=> OM-503 Added global storage

openIMIS/server.py
[https://openimis.atlassian.net/browse/OM-123](https://openimis.atlassian.net/browse/OM-123)
=> Added trusted proxy for waitress setup

openimis.json
https://openimis.atlassian.net/browse/CM-855
it needs: https://github.com/openimis/openimis-be-grievance_social_protection_py/pull/4
=> CM-855: add grievance_social_protection

openIMIS/openIMIS/asgi.py, openIMIS/openIMIS/settings.py
=> Fixed django channels setup

openIMIS/openIMIS/settings.py
Debug is now based on the environment variable. True if mode is DEV otherwise False in PROD
=> Environment var MODE is introduced

Dockerfile, openIMIS/openIMIS/settings.py, openimis.json, requirements.txt
Create CACHE and Worker related settings only if the env variables are set.
=> Fix settings
